# Preprocessing

In [34]:
import warnings
warnings.filterwarnings('ignore')

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor

from sklearn.preprocessing import LabelEncoder, StandardScaler

from sklearn.metrics import (accuracy_score, f1_score, fbeta_score,
                             confusion_matrix, precision_recall_fscore_support)
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
import xgboost as xgb

RANDOM_STATE = 67

In [2]:
df = pd.read_csv('filtered_data.csv')

df.head()

,_BMI5,_BMI5CAT,_AGE_G,_AGE80,_AGE65YR,_INCOMG1,INCOME3,_SMOKER3,_RFSMOK3,SMOKDAY2,...,MENTHLTH,ADDEPEV3,LANDSEX3,SEXVAR,DIABETE4,PERSDOC3,PRIMINS2,_URBSTAT,_IMPRACE,CHILDREN
0,2249.0,2.0,6.0,78.0,2.0,9.0,99.0,4.0,1.0,NaN,...,88.0,2.0,2.0,2.0,3.0,2.0,3.0,1.0,1.0,88.0
1,2583.0,3.0,6.0,80.0,2.0,7.0,11.0,3.0,1.0,3.0,...,88.0,2.0,1.0,1.0,3.0,1.0,3.0,1.0,1.0,88.0
2,2253.0,2.0,5.0,59.0,1.0,9.0,99.0,1.0,2.0,1.0,...,88.0,2.0,1.0,1.0,3.0,3.0,1.0,1.0,1.0,88.0
3,2509.0,3.0,6.0,80.0,2.0,4.0,6.0,4.0,1.0,NaN,...,88.0,2.0,1.0,1.0,3.0,1.0,3.0,1.0,1.0,88.0
4,1977.0,2.0,4.0,47.0,1.0,2.0,3.0,4.0,1.0,NaN,...,88.0,2.0,1.0,1.0,3.0,1.0,5.0,1.0,1.0,88.0

In [3]:
df.columns

Index(['_BMI5', '_BMI5CAT', '_AGE_G', '_AGE80', '_AGE65YR', '_INCOMG1',
       'INCOME3', '_SMOKER3', '_RFSMOK3', 'SMOKDAY2', 'CVDINFR4', 'CVDCRHD4',
       'ASTHMA3', '_LTASTH1', 'CHCKDNY2', 'MARITAL', 'EDUCA', '_EDUCAG',
       'GENHLTH', 'EXERANY2', '_TOTINDA', 'HAVARTH4', '_DRDXAR2', 'MENTHLTH',
       'ADDEPEV3', 'LANDSEX3', 'SEXVAR', 'DIABETE4', 'PERSDOC3', 'PRIMINS2',
       '_URBSTAT', '_IMPRACE', 'CHILDREN'],
      dtype='str')

In [4]:
chosen_columns = ['_BMI5', '_AGE_G', 'INCOME3', '_SMOKER3', 'CVDINFR4', 'CVDCRHD4',
                 'ASTHMA3', 'CHCKDNY2', 'MARITAL', 'EDUCA', 'GENHLTH', 'EXERANY2',
                 'HAVARTH4', 'MENTHLTH', 'ADDEPEV3', 'SEXVAR', 'PERSDOC3', 'PRIMINS2',
                 '_URBSTAT', 'CHILDREN', 'DIABETE4']

df_eda = df[chosen_columns]

In [5]:
df_eda.head()

,_BMI5,_AGE_G,INCOME3,_SMOKER3,CVDINFR4,CVDCRHD4,ASTHMA3,CHCKDNY2,MARITAL,EDUCA,...,EXERANY2,HAVARTH4,MENTHLTH,ADDEPEV3,SEXVAR,PERSDOC3,PRIMINS2,_URBSTAT,CHILDREN,DIABETE4
0,2249.0,6.0,99.0,4.0,2.0,2.0,2.0,2.0,3.0,4.0,...,1.0,1.0,88.0,2.0,2.0,2.0,3.0,1.0,88.0,3.0
1,2583.0,6.0,11.0,3.0,2.0,1.0,2.0,2.0,1.0,6.0,...,1.0,1.0,88.0,2.0,1.0,1.0,3.0,1.0,88.0,3.0
2,2253.0,5.0,99.0,1.0,2.0,2.0,2.0,2.0,6.0,5.0,...,1.0,1.0,88.0,2.0,1.0,3.0,1.0,1.0,88.0,3.0
3,2509.0,6.0,6.0,4.0,2.0,2.0,2.0,2.0,1.0,6.0,...,1.0,1.0,88.0,2.0,1.0,1.0,3.0,1.0,88.0,3.0
4,1977.0,4.0,3.0,4.0,2.0,2.0,2.0,2.0,5.0,5.0,...,2.0,2.0,88.0,2.0,1.0,1.0,5.0,1.0,88.0,3.0

In [6]:
# 80/20 split
df_train, df_test = train_test_split(df_eda, test_size=0.2, random_state=RANDOM_STATE)

# Save to CSV
df_train.to_csv('df_train.csv', index=False)
df_test.to_csv('df_test.csv', index=False)

Splitting the data early since it makes the modeling forward more robust.

In [7]:
df_train = pd.read_csv('df_train.csv')
df_test = pd.read_csv('df_test.csv')

df_train.head()

,_BMI5,_AGE_G,INCOME3,_SMOKER3,CVDINFR4,CVDCRHD4,ASTHMA3,CHCKDNY2,MARITAL,EDUCA,...,EXERANY2,HAVARTH4,MENTHLTH,ADDEPEV3,SEXVAR,PERSDOC3,PRIMINS2,_URBSTAT,CHILDREN,DIABETE4
0,2363.0,6.0,9.0,1.0,2.0,2.0,1.0,2.0,1.0,5.0,...,1.0,2.0,88.0,2.0,1.0,1.0,1.0,1.0,88.0,3.0
1,4750.0,5.0,1.0,4.0,2.0,1.0,2.0,2.0,1.0,4.0,...,2.0,1.0,25.0,1.0,1.0,2.0,77.0,1.0,88.0,3.0
2,2789.0,5.0,3.0,4.0,2.0,2.0,2.0,2.0,3.0,4.0,...,1.0,2.0,88.0,2.0,1.0,1.0,3.0,1.0,88.0,1.0
3,3068.0,1.0,10.0,4.0,2.0,2.0,2.0,2.0,5.0,6.0,...,1.0,2.0,88.0,2.0,1.0,2.0,1.0,1.0,88.0,3.0
4,2729.0,5.0,6.0,4.0,2.0,2.0,2.0,2.0,1.0,5.0,...,1.0,2.0,88.0,2.0,2.0,1.0,5.0,NaN,88.0,3.0

# Unknown Values Handling
Unknown values here are responds with the description of "Don't know", "Refused", pure NaN, or other with similar meaning. There'll be 3 ways of handling unknown values:

a. Unify and Use Unknown Values

b. Standard Imputation for Unknown Values

c. Advanced Imputation for Unknown Values

d. Keeping don't know/refused labels

## a. Using missing values

In [8]:
df_train_unify = df_train.copy()
df_test_unify = df_test.copy()

In [9]:
def preprocess_df_unify(df):
    # DIABETE4
    df['DIABETE4'] = df['DIABETE4'].map({
        1: 1, 2: np.nan, 3: 0, 4: 1, 7: np.nan, 9: np.nan
    })

    # Binary columns
    binary_cols = [
        'EXERANY2', 'CVDINFR4', 'CVDCRHD4',
        'ASTHMA3', 'CHCKDNY2', 'HAVARTH4', 'ADDEPEV3'
    ]
    binary_map = {1: 1, 2: 0, 7: np.nan, 9: np.nan}
    for col in binary_cols:
        df[col] = df[col].map(binary_map)

    # Age
    df['_AGE_G'] = df['_AGE_G'].map({1:1, 2:2, 3:3, 4:4, 5:5, 6:6})

    # Income
    df['INCOME3'] = df['INCOME3'].replace({77: np.nan, 99: np.nan})

    # General Health
    df['GENHLTH'] = df['GENHLTH'].map({1:5, 2:4, 3:3, 4:2, 5:1, 7:np.nan, 9:np.nan})

    # Education
    df['EDUCA'] = df['EDUCA'].replace({9: np.nan})

    # Sex
    df['SEXVAR'] = df['SEXVAR'].map({1:0, 2:1})

    # Urban/Rural
    df['_URBSTAT'] = df['_URBSTAT'].map({1:0, 2:1})

    # Nominal columns
    nominal_cols = ['MARITAL', 'PRIMINS2', '_SMOKER3', 'PERSDOC3']
    for col in nominal_cols:
        df[col] = df[col].replace({7: np.nan, 9: np.nan, 77: np.nan, 99: np.nan})

    # BMI scaling
    df['_BMI5'] = df['_BMI5'] / 100.0

    # Children
    df['CHILDREN'] = df['CHILDREN'].replace({88: 0, 99: np.nan})

    # Mental health
    df['MENTHLTH'] = df['MENTHLTH'].replace({88: 0, 77: np.nan, 99: np.nan})

    return df

In [10]:
# Apply to train/test
df_train_unify = preprocess_df_unify(df_train_unify)
df_test_unify = preprocess_df_unify(df_test_unify)

df_test_unify.head()

,_BMI5,_AGE_G,INCOME3,_SMOKER3,CVDINFR4,CVDCRHD4,ASTHMA3,CHCKDNY2,MARITAL,EDUCA,...,EXERANY2,HAVARTH4,MENTHLTH,ADDEPEV3,SEXVAR,PERSDOC3,PRIMINS2,_URBSTAT,CHILDREN,DIABETE4
0,14.47,6,NaN,3.0,0.0,0.0,0.0,1.0,3.0,5.0,...,0.0,1.0,15.0,0.0,1,1.0,NaN,0.0,1.0,0.0
1,28.17,6,7.0,4.0,0.0,0.0,1.0,0.0,3.0,5.0,...,0.0,0.0,0.0,0.0,1,1.0,3.0,0.0,0.0,0.0
2,28.70,3,3.0,4.0,0.0,0.0,0.0,0.0,1.0,5.0,...,1.0,0.0,0.0,0.0,0,3.0,88.0,0.0,0.0,0.0
3,32.50,4,NaN,NaN,0.0,0.0,0.0,0.0,1.0,4.0,...,1.0,0.0,0.0,0.0,0,2.0,2.0,0.0,1.0,0.0
4,23.06,2,NaN,4.0,0.0,0.0,0.0,0.0,5.0,6.0,...,1.0,0.0,20.0,0.0,0,1.0,1.0,0.0,0.0,0.0

In [11]:
df_train_unify.isna().sum()

_BMI5       34537
_AGE_G          0
INCOME3     70040
_SMOKER3    25739
CVDINFR4     2496
CVDCRHD4     3687
ASTHMA3      1484
CHCKDNY2     1594
MARITAL      3337
EDUCA        1900
GENHLTH      1046
EXERANY2     1059
HAVARTH4     2048
MENTHLTH     6540
ADDEPEV3     2139
SEXVAR          0
PERSDOC3     3698
PRIMINS2    38289
_URBSTAT    11720
CHILDREN     7501
DIABETE4     3581
dtype: int64

## b. Standard Imputation for Unknown Values

In [12]:
df_train_simple_impute = df_train_unify.copy()
df_test_simple_impute = df_test_unify.copy()

In [13]:
def simple_impute(df_train, df_test):
    df_train = df_train.copy()
    df_test = df_test.copy()

    # --- 1. Columns by type / strategy ---
    numeric_cols = ['_BMI5', 'CHILDREN', 'MENTHLTH']  # median
    ordinal_mode_cols = ['_AGE_G', 'GENHLTH', 'EDUCA', 'INCOME3']  # mode
    cat_mode_cols = [
        '_SMOKER3', 'MARITAL', 'SEXVAR', 'PERSDOC3', 'PRIMINS2',
        '_URBSTAT', 'EXERANY2', 'CVDINFR4', 'CVDCRHD4', 'ASTHMA3',
        'CHCKDNY2', 'HAVARTH4', 'ADDEPEV3'
    ]  # mode

    # --- 2. Numeric: median ---
    num_imputer = SimpleImputer(strategy='median')
    df_train[numeric_cols] = num_imputer.fit_transform(df_train[numeric_cols])
    df_test[numeric_cols] = num_imputer.transform(df_test[numeric_cols])

    # --- 3. Ordinal: mode ---
    ord_imputer = SimpleImputer(strategy='most_frequent')
    df_train[ordinal_mode_cols] = ord_imputer.fit_transform(df_train[ordinal_mode_cols])
    df_test[ordinal_mode_cols] = ord_imputer.transform(df_test[ordinal_mode_cols])

    # --- 4. Categorical: mode ---
    cat_imputer = SimpleImputer(strategy='most_frequent')
    df_train[cat_mode_cols] = cat_imputer.fit_transform(df_train[cat_mode_cols])
    df_test[cat_mode_cols] = cat_imputer.transform(df_test[cat_mode_cols])

    return df_train, df_test

In [14]:
df_train_simple_impute, df_test_simple_impute = simple_impute(df_train_simple_impute, df_test_simple_impute)

df_test_simple_impute.head()

,_BMI5,_AGE_G,INCOME3,_SMOKER3,CVDINFR4,CVDCRHD4,ASTHMA3,CHCKDNY2,MARITAL,EDUCA,...,EXERANY2,HAVARTH4,MENTHLTH,ADDEPEV3,SEXVAR,PERSDOC3,PRIMINS2,_URBSTAT,CHILDREN,DIABETE4
0,14.47,6.0,7.0,3.0,0.0,0.0,0.0,1.0,3.0,5.0,...,0.0,1.0,15.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0
1,28.17,6.0,7.0,4.0,0.0,0.0,1.0,0.0,3.0,5.0,...,0.0,0.0,0.0,0.0,1.0,1.0,3.0,0.0,0.0,0.0
2,28.70,3.0,3.0,4.0,0.0,0.0,0.0,0.0,1.0,5.0,...,1.0,0.0,0.0,0.0,0.0,3.0,88.0,0.0,0.0,0.0
3,32.50,4.0,7.0,4.0,0.0,0.0,0.0,0.0,1.0,4.0,...,1.0,0.0,0.0,0.0,0.0,2.0,2.0,0.0,1.0,0.0
4,23.06,2.0,7.0,4.0,0.0,0.0,0.0,0.0,5.0,6.0,...,1.0,0.0,20.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0

In [15]:
df_test_simple_impute.isna().sum()

_BMI5         0
_AGE_G        0
INCOME3       0
_SMOKER3      0
CVDINFR4      0
CVDCRHD4      0
ASTHMA3       0
CHCKDNY2      0
MARITAL       0
EDUCA         0
GENHLTH       0
EXERANY2      0
HAVARTH4      0
MENTHLTH      0
ADDEPEV3      0
SEXVAR        0
PERSDOC3      0
PRIMINS2      0
_URBSTAT      0
CHILDREN      0
DIABETE4    848
dtype: int64

## c. Random Forest Imputation for Unknown Values

In [16]:
df_train_adv_impute = df_train_unify.copy()
df_test_adv_impute = df_test_unify.copy()

In [17]:
def predictive_impute(train_df, test_df, target_col, feature_cols, categorical_model, regression_model, is_categorical=True):
    train_df = train_df.copy()
    test_df = test_df.copy()

    known = train_df[train_df[target_col].notna()]
    unknown = train_df[train_df[target_col].isna()]

    model = categorical_model if is_categorical else regression_model
    le = LabelEncoder() if is_categorical else None

    if unknown.shape[0] > 0:
        X_known = known[feature_cols].copy()
        y_known = known[target_col]
        X_unknown = unknown[feature_cols].copy()

        # Encode categoricals as integers
        for col in X_known.columns:
            if X_known[col].dtype == 'object' or X_known[col].dtype.name == 'category':
                cats = list(X_known[col].dropna().unique())
                mapping = {k:i for i,k in enumerate(cats)}
                X_known[col] = X_known[col].map(mapping)
                X_unknown[col] = X_unknown[col].map(mapping)

        #  target encoding for xgberror
        if is_categorical:
            y_train_encoded = le.fit_transform(y_known)
        else:
            y_train_encoded = y_known

        #  TRAIN MODEL
        model.fit(X_known, y_train_encoded)

        #  PREDICT & DECODE
        preds = model.predict(X_unknown)
        if is_categorical:
            preds = le.inverse_transform(preds)
        
        train_df.loc[train_df[target_col].isna(), target_col] = preds

    # PREDICT MISSING IN TEST
    test_unknown = test_df[test_df[target_col].isna()]
    if test_unknown.shape[0] > 0:
        X_test_unknown = test_unknown[feature_cols].copy()
        for col in X_test_unknown.columns:
            if X_test_unknown[col].dtype == 'object' or X_test_unknown[col].dtype.name == 'category':
                # Gunakan mapping dari train untuk konsistensi
                cats = list(known[col].dropna().unique())
                mapping = {k:i for i,k in enumerate(cats)}
                X_test_unknown[col] = X_test_unknown[col].map(mapping)
        
        test_preds = model.predict(X_test_unknown)
        if is_categorical:
            test_preds = le.inverse_transform(test_preds)
            
        test_df.loc[test_df[target_col].isna(), target_col] = test_preds

    return train_df[target_col], test_df[target_col]

def adv_impute(df_train, df_test, categorical_model, regression_model):
    """
    Train/test-safe imputation:
    - Simple imputation (median/mode) for most columns
    - Predictive imputation for tricky columns (_BMI5, INCOME3, _SMOKER3)
    """
    df_train = df_train.copy()
    df_test = df_test.copy()

    # --- 1. Columns by type for simple imputation ---
    numeric_cols = ['CHILDREN', 'MENTHLTH']  # median only
    ordinal_mode_cols = ['_AGE_G', 'GENHLTH', 'EDUCA']  # mode only
    cat_mode_cols = [
        'MARITAL', 'SEXVAR', 'PERSDOC3', 'PRIMINS2',
        '_URBSTAT', 'EXERANY2', 'CVDINFR4', 'CVDCRHD4', 'ASTHMA3',
        'CHCKDNY2', 'HAVARTH4', 'ADDEPEV3'
    ]  # mode only

    # --- 2. Simple imputation ---
    # Numeric
    num_imputer = SimpleImputer(strategy='median')
    df_train[numeric_cols] = num_imputer.fit_transform(df_train[numeric_cols])
    df_test[numeric_cols] = num_imputer.transform(df_test[numeric_cols])

    # Ordinal
    ord_imputer = SimpleImputer(strategy='most_frequent')
    df_train[ordinal_mode_cols] = ord_imputer.fit_transform(df_train[ordinal_mode_cols])
    df_test[ordinal_mode_cols] = ord_imputer.transform(df_test[ordinal_mode_cols])

    # Categorical
    cat_imputer = SimpleImputer(strategy='most_frequent')
    df_train[cat_mode_cols] = cat_imputer.fit_transform(df_train[cat_mode_cols])
    df_test[cat_mode_cols] = cat_imputer.transform(df_test[cat_mode_cols])

    # --- 3. Apply predictive imputation on tricky columns ---
    # INCOME3 -> categorical
    df_train['INCOME3'], df_test['INCOME3'] = predictive_impute(
        df_train, df_test, 'INCOME3',
        ['PRIMINS2', 'EDUCA', 'MARITAL', 'GENHLTH', '_AGE_G', 'EXERANY2', 'SEXVAR', '_URBSTAT'],
        categorical_model, regression_model, is_categorical=True, 
    )

    # _BMI5 -> numeric
    df_train['_BMI5'], df_test['_BMI5'] = predictive_impute(
        df_train, df_test, '_BMI5',
        ['GENHLTH', 'EXERANY2', 'HAVARTH4', '_AGE_G', 'ASTHMA3', '_SMOKER3'],
        categorical_model, regression_model, is_categorical=False
    )

    # _SMOKER3 -> categorical
    df_train['_SMOKER3'], df_test['_SMOKER3'] = predictive_impute(
        df_train, df_test, '_SMOKER3',
        ['_AGE_G', 'EDUCA', 'ADDEPEV3', 'SEXVAR', 'HAVARTH4'],
        categorical_model, regression_model, is_categorical=True
    )

    return df_train, df_test

In [18]:
cat_model = RandomForestClassifier(random_state=RANDOM_STATE)
reg_model = RandomForestRegressor(random_state=RANDOM_STATE)
df_train_rf_impute, df_test_rf_impute = adv_impute(df_train_adv_impute, df_test_adv_impute, cat_model, reg_model)

df_test_rf_impute.head()

,_BMI5,_AGE_G,INCOME3,_SMOKER3,CVDINFR4,CVDCRHD4,ASTHMA3,CHCKDNY2,MARITAL,EDUCA,...,EXERANY2,HAVARTH4,MENTHLTH,ADDEPEV3,SEXVAR,PERSDOC3,PRIMINS2,_URBSTAT,CHILDREN,DIABETE4
0,14.47,6.0,5.0,3.0,0.0,0.0,0.0,1.0,3.0,5.0,...,0.0,1.0,15.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0
1,28.17,6.0,7.0,4.0,0.0,0.0,1.0,0.0,3.0,5.0,...,0.0,0.0,0.0,0.0,1.0,1.0,3.0,0.0,0.0,0.0
2,28.70,3.0,3.0,4.0,0.0,0.0,0.0,0.0,1.0,5.0,...,1.0,0.0,0.0,0.0,0.0,3.0,88.0,0.0,0.0,0.0
3,32.50,4.0,7.0,4.0,0.0,0.0,0.0,0.0,1.0,4.0,...,1.0,0.0,0.0,0.0,0.0,2.0,2.0,0.0,1.0,0.0
4,23.06,2.0,9.0,4.0,0.0,0.0,0.0,0.0,5.0,6.0,...,1.0,0.0,20.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0

## d. XGB imputation for unknown values

In [19]:
df_train_xgb_impute = df_train_unify.copy()
df_test_xgb_impute = df_test_unify.copy()

cat_model = xgb.XGBClassifier(random_state=RANDOM_STATE)
reg_model = xgb.XGBRegressor(random_state=RANDOM_STATE)
df_train_xgb_impute, df_test_xgb_impute = adv_impute(df_train_xgb_impute, df_test_xgb_impute, cat_model, reg_model)

df_test_xgb_impute.head()

,_BMI5,_AGE_G,INCOME3,_SMOKER3,CVDINFR4,CVDCRHD4,ASTHMA3,CHCKDNY2,MARITAL,EDUCA,...,EXERANY2,HAVARTH4,MENTHLTH,ADDEPEV3,SEXVAR,PERSDOC3,PRIMINS2,_URBSTAT,CHILDREN,DIABETE4
0,14.47,6.0,5.0,3.0,0.0,0.0,0.0,1.0,3.0,5.0,...,0.0,1.0,15.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0
1,28.17,6.0,7.0,4.0,0.0,0.0,1.0,0.0,3.0,5.0,...,0.0,0.0,0.0,0.0,1.0,1.0,3.0,0.0,0.0,0.0
2,28.70,3.0,3.0,4.0,0.0,0.0,0.0,0.0,1.0,5.0,...,1.0,0.0,0.0,0.0,0.0,3.0,88.0,0.0,0.0,0.0
3,32.50,4.0,11.0,4.0,0.0,0.0,0.0,0.0,1.0,4.0,...,1.0,0.0,0.0,0.0,0.0,2.0,2.0,0.0,1.0,0.0
4,23.06,2.0,7.0,4.0,0.0,0.0,0.0,0.0,5.0,6.0,...,1.0,0.0,20.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0

## e. Keeping the refused/don't know label

People that refuses to answer might just be insecure/keeping info from sensitive information, while people who answers don't know might jsut be because they are unaware. I think those characteristic could possibly translate to a signal on their own.

In [20]:
def preprocess_df_refused(df):
    # DIABETE4
    df['DIABETE4'] = df['DIABETE4'].map({
        1: 1, 2: np.nan, 3: 0, 4: 1, 7: np.nan, 9: np.nan
    })

    # Binary columns
    binary_cols = [
        'EXERANY2', 'CVDINFR4', 'CVDCRHD4',
        'ASTHMA3', 'CHCKDNY2', 'HAVARTH4', 'ADDEPEV3'
    ]
    binary_map = {1: 1, 2: 0, 7: np.nan, 9: np.nan}
    for col in binary_cols:
        df[col] = df[col].map(binary_map)

    # Age
    df['_AGE_G'] = df['_AGE_G'].map({1:1, 2:2, 3:3, 4:4, 5:5, 6:6})

    # Income
    df['INCOME3'] = df['INCOME3'].replace({77: -2, 99: -1})

    # General Health
    df['GENHLTH'] = df['GENHLTH'].map({1:5, 2:4, 3:3, 4:2, 5:1, 7:-2, 9:-1})

    # Education
    df['EDUCA'] = df['EDUCA'].replace({9: -1})

    # Sex
    df['SEXVAR'] = df['SEXVAR'].map({1:0, 2:1})

    # Urban/Rural
    df['_URBSTAT'] = df['_URBSTAT'].map({1:0, 2:1})

    # Nominal columns
    nominal_cols = ['MARITAL', 'PRIMINS2', '_SMOKER3', 'PERSDOC3']
    for col in nominal_cols:
        df[col] = df[col].replace({7: -2, 9: -1, 77: -2, 99: -1})

    # BMI scaling
    df['_BMI5'] = df['_BMI5'] / 100.0

    # Children
    df['CHILDREN'] = df['CHILDREN'].replace({88: 0, 99: -1})

    # Mental health
    df['MENTHLTH'] = df['MENTHLTH'].replace({88: 0, 77: -2, 99: -1})

    return df

In [21]:
df_train = pd.read_csv('df_train.csv')
df_test = pd.read_csv('df_test.csv')

df_train_refused = preprocess_df_refused(df_train.copy())
df_test_refused = preprocess_df_refused(df_test.copy())

In [22]:
df_train_refused.isna().sum()

_BMI5       34537
_AGE_G          0
INCOME3      7478
_SMOKER3        0
CVDINFR4     2496
CVDCRHD4     3687
ASTHMA3      1484
CHCKDNY2     1594
MARITAL         7
EDUCA           5
GENHLTH         4
EXERANY2     1059
HAVARTH4     2048
MENTHLTH        2
ADDEPEV3     2139
SEXVAR          0
PERSDOC3        1
PRIMINS2        2
_URBSTAT    11720
CHILDREN     4498
DIABETE4     3581
dtype: int64

In [23]:
cat_model = RandomForestClassifier(random_state=RANDOM_STATE)
reg_model = RandomForestRegressor(random_state=RANDOM_STATE)
df_train_refused, df_test_refused = adv_impute(df_train_refused, df_test_refused, cat_model, reg_model)

In [24]:
df_train_refused.isna().sum()

_BMI5          0
_AGE_G         0
INCOME3        0
_SMOKER3       0
CVDINFR4       0
CVDCRHD4       0
ASTHMA3        0
CHCKDNY2       0
MARITAL        0
EDUCA          0
GENHLTH        0
EXERANY2       0
HAVARTH4       0
MENTHLTH       0
ADDEPEV3       0
SEXVAR         0
PERSDOC3       0
PRIMINS2       0
_URBSTAT       0
CHILDREN       0
DIABETE4    3581
dtype: int64

## One Hot Encode

In [25]:
def one_hot_encode_nominal(df_train, df_test):
    """
    One-Hot Encodes nominal columns after imputation is complete.
    Combines train and test sets temporarily to ensure the dummy columns align perfectly.
    """
    # The columns that have no mathematical order
    nominal_cols = ['MARITAL', 'PRIMINS2', '_SMOKER3', 'PERSDOC3']

    df_train = df_train.copy()
    df_test = df_test.copy()

    # Add tracker column to easily split them back apart later
    df_train['is_train_set'] = 1
    df_test['is_train_set'] = 0

    # Combine datasets to guarantee identical columns
    combined_df = pd.concat([df_train, df_test])

    # Apply One-Hot Encoding (drop_first=True prevents multicollinearity for LR/SVM)
    combined_encoded = pd.get_dummies(combined_df, columns=nominal_cols, drop_first=True)

    # Split them back into train and test
    df_train_encoded = combined_encoded[combined_encoded['is_train_set'] == 1].drop(columns=['is_train_set'])
    df_test_encoded = combined_encoded[combined_encoded['is_train_set'] == 0].drop(columns=['is_train_set'])

    return df_train_encoded, df_test_encoded

In [26]:
# 2. Execute the Encoding
# A. Encode the Simple Imputation datasets
df_train_simple_encoded, df_test_simple_encoded = one_hot_encode_nominal(
    df_train_simple_impute,
    df_test_simple_impute
)

# B. Encode the Advanced Imputation datasets
df_train_rf_encoded, df_test_rf_encoded = one_hot_encode_nominal(
    df_train_rf_impute,
    df_test_rf_impute
)

df_train_xgb_encoded, df_test_xgb_encoded = one_hot_encode_nominal(
    df_train_xgb_impute,
    df_test_xgb_impute
)

df_train_refused_encoded, df_test_refused_encoded = one_hot_encode_nominal(
    df_train_refused,
    df_test_refused,
)

# Note: We purposely DO NOT one hot encode df_train_unify or df_test_unify here.
# We leave them exactly as they are so XGBoost can use its native categorical handling.

# Modelling
We'll use XGBoost, Logistic Regression, and Support Vector Machine.

In [27]:
target_col = "DIABETE4"
datasets = {
    "Missing_values": (df_train_unify, df_test_unify),
    "Simple_imputed": (df_train_simple_encoded, df_test_simple_encoded),
    "RF_imputed": (df_train_rf_encoded, df_test_rf_encoded),
    "XGB_imputed": (df_train_xgb_encoded, df_test_xgb_encoded),
    "Refused_keep": (df_train_refused_encoded, df_test_refused_encoded)
}

# Define feature sets
feature_cols_unify = [c for c in df_train_unify.columns if c != target_col]
feature_cols_encoded = [c for c in df_train_simple_encoded.columns if c != target_col]

In [32]:
def get_metrics(y_true, y_pred, y_prob, model_name, dataset_name):
    """Returns performance metrics with F1-Macro/Micro and F2-score."""
    
    # Confusion Matrix
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
    precision, recall, f1, _ = precision_recall_fscore_support(y_true, y_pred, labels=[0, 1])

    f2_score_val = fbeta_score(y_true, y_pred, beta=2)

    return {
        "Dataset": dataset_name,
        "Model": model_name,
        "F1_Macro": f1_score(y_true, y_pred, average='macro'),
        "F2_Score": f2_score_val,
        "Prec_0": precision[0], "Rec_0": recall[0], "F1_0": f1[0],
        "Prec_1": precision[1], "Rec_1": recall[1], "F1_1": f1[1]
    }

In [35]:
results = []

for dataset_name, (df_train, df_test) in datasets.items():
    print(f"Processing dataset: {dataset_name}...")
    # 1. Clean and Encode
    df_train = df_train.dropna(subset=[target_col])
    df_test = df_test.dropna(subset=[target_col])

    # 2. Split X and y
    cols = feature_cols_unify if dataset_name == "Missing_values" else feature_cols_encoded
    X_train, y_train = df_train[cols], df_train[target_col].astype(int)
    X_test, y_test = df_test[cols], df_test[target_col].astype(int)

    # Unify has NaN values, so it's only thrown to xgboost
    if dataset_name != "Missing_values":
        # --- 1. Logistic Regression ---
        lr = LogisticRegression(max_iter=1000, random_state=RANDOM_STATE)
        lr.fit(X_train, y_train)
        y_pred = lr.predict(X_test)
        y_proba = lr.predict_proba(X_test)[:, 1]
        results.append(get_metrics(y_test,  y_pred, y_proba, "LogisticRegression", dataset_name))
        
        # --- 2. SVM ---
        svm = LinearSVC(max_iter=2000, random_state=RANDOM_STATE) 
        svm.fit(X_train, y_train)
        y_pred = svm.predict(X_test)
        y_proba = svm.decision_function(X_test)
        results.append(get_metrics(y_test,  y_pred, y_proba, "SVM", dataset_name))
        
    # --- 3. XGBoost ---
    xgb_model = xgb.XGBClassifier(random_state=RANDOM_STATE)
    xgb_model.fit(X_train, y_train)
    y_pred = xgb_model.predict(X_test)
    y_proba = xgb_model.predict_proba(X_test)[:, 1]
    results.append(get_metrics(y_test, y_pred, y_proba, "XGBoost", dataset_name))

display(pd.DataFrame(results))

Processing dataset: Missing_values...
Processing dataset: Simple_imputed...
Processing dataset: RF_imputed...
Processing dataset: XGB_imputed...
Processing dataset: Refused_keep...

,Dataset,Model,F1_Macro,F2_Score,Prec_0,Rec_0,F1_0,Prec_1,Rec_1,F1_1
0,Missing_values,XGBoost,0.577988,0.187797,0.850051,0.972306,0.907078,0.543764,0.161385,0.248898
1,Simple_imputed,LogisticRegression,0.574676,0.183517,0.849371,0.971337,0.906269,0.529540,0.157748,0.243082
2,Simple_imputed,SVM,0.543195,0.125794,0.843231,0.984340,0.908338,0.578778,0.105208,0.178051
3,Simple_imputed,XGBoost,0.576421,0.185152,0.849716,0.972532,0.906985,0.542073,0.158982,0.245857
4,RF_imputed,LogisticRegression,0.574515,0.183470,0.849341,0.971111,0.906154,0.527585,0.157748,0.242876
5,RF_imputed,SVM,0.542761,0.124996,0.843157,0.984579,0.908397,0.580866,0.104494,0.177125
6,RF_imputed,XGBoost,0.578855,0.188819,0.850226,0.972665,0.907334,0.548288,0.162229,0.250376
7,XGB_imputed,LogisticRegression,0.574374,0.183252,0.849312,0.971111,0.906137,0.527277,0.157553,0.242612
8,XGB_imputed,SVM,0.542908,0.125157,0.843185,0.984646,0.908441,0.582219,0.104624,0.177374
9,XGB_imputed,XGBoost,0.577151,0.186311,0.849870,0.972506,0.907061,0.543449,0.160021,0.247241
10,Refused_keep,LogisticRegression,0.571383,0.177405,0.848663,0.972466,0.906356,0.530464,0.152098,0.236410
11,Refused_keep,SVM,0.539955,0.120663,0.842662,0.985031,0.908301,0.579164,0.100727,0.171609
12,Refused_keep,XGBoost,0.577816,0.186861,0.849999,0.973037,0.907366,0.548889,0.160410,0.248266

In [36]:
display(pd.DataFrame(results).sort_values(['F2_Score'], ascending=False))

,Dataset,Model,F1_Macro,F2_Score,Prec_0,Rec_0,F1_0,Prec_1,Rec_1,F1_1
6,RF_imputed,XGBoost,0.578855,0.188819,0.850226,0.972665,0.907334,0.548288,0.162229,0.250376
0,Missing_values,XGBoost,0.577988,0.187797,0.850051,0.972306,0.907078,0.543764,0.161385,0.248898
12,Refused_keep,XGBoost,0.577816,0.186861,0.849999,0.973037,0.907366,0.548889,0.160410,0.248266
9,XGB_imputed,XGBoost,0.577151,0.186311,0.849870,0.972506,0.907061,0.543449,0.160021,0.247241
3,Simple_imputed,XGBoost,0.576421,0.185152,0.849716,0.972532,0.906985,0.542073,0.158982,0.245857
1,Simple_imputed,LogisticRegression,0.574676,0.183517,0.849371,0.971337,0.906269,0.529540,0.157748,0.243082
4,RF_imputed,LogisticRegression,0.574515,0.183470,0.849341,0.971111,0.906154,0.527585,0.157748,0.242876
7,XGB_imputed,LogisticRegression,0.574374,0.183252,0.849312,0.971111,0.906137,0.527277,0.157553,0.242612
10,Refused_keep,LogisticRegression,0.571383,0.177405,0.848663,0.972466,0.906356,0.530464,0.152098,0.236410
2,Simple_imputed,SVM,0.543195,0.125794,0.843231,0.984340,0.908338,0.578778,0.105208,0.178051
8,XGB_imputed,SVM,0.542908,0.125157,0.843185,0.984646,0.908441,0.582219,0.104624,0.177374
5,RF_imputed,SVM,0.542761,0.124996,0.843157,0.984579,0.908397,0.580866,0.104494,0.177125
11,Refused_keep,SVM,0.539955,0.120663,0.842662,0.985031,0.908301,0.579164,0.100727,0.171609

In [40]:
final_comparison = pd.DataFrame(results).groupby('Dataset').mean(numeric_only=True).sort_values(by='F2_Score', ascending=False)

final_comparison

,F1_Macro,F2_Score,Prec_0,Rec_0,F1_0,Prec_1,Rec_1,F1_1
Dataset,,,,,,,,
Missing_values,0.577988,0.187797,0.850051,0.972306,0.907078,0.543764,0.161385,0.248898
RF_imputed,0.565377,0.165762,0.847575,0.976118,0.907295,0.552246,0.141490,0.223459
XGB_imputed,0.564811,0.164907,0.847456,0.976087,0.907213,0.550982,0.140733,0.222409
Simple_imputed,0.564764,0.164821,0.847439,0.976070,0.907197,0.550130,0.140646,0.222330
Refused_keep,0.563051,0.161643,0.847108,0.976844,0.907341,0.552839,0.137745,0.218762